services:
  web:
    build: .
    container_name: web
    depends_on:
      - db
    environment:
      - DJANGO_SETTINGS_MODULE=pingpong.settings
    expose:
      - "8000"
    networks:
      - pingpong_network
    volumes:
      - ./regidtration/media:/app/regidtration/media
      - ./staticfiles:/app/staticfiles
    command: gunicorn --workers 3 pingpong.wsgi:application --bind 0.0.0.0:8000

  nginx:
    image: nginx:alpine
    volumes:
      - ./nginx/certs:/etc/ssl/certs
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./staticfiles:/static
    ports:
      - "443:443"
      - "80:80"
    networks:
      - pingpong_network
    depends_on:
      - web

  db:
    image: postgres:15
    container_name: db
    environment:
      POSTGRES_USER: mhromylo
      POSTGRES_PASSWORD: qwerty
      POSTGRES_DB: table
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - pingpong_network

volumes:
  postgres_data:

networks:
  pingpong_network:
    driver: bridge